apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: ns-devops
  name: cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            command: ['sh', '-c', 'date;curl -s -o /dev/null -w "Status %{http_code}\n" http://10.99.140.247:30081']
          restartPolicy: OnFailure
